import { User } from '../UserRepository.interface';

export const data: User[] = [
    {
        id: 1,
        login: 'zverkovep@edu.hse.ru',
        password: '123',
        role: 'creator',
        registeredEvents: [101],
        createdEvents: [],
        createdDate: '2025-01-15T09:30:00Z',
        fullName: 'Зверьков Егор Павлович',
        educationalProgram: 'Бизнес-информатика',
        group: '22БИ',
        course: 3,
    },
    {
        id: 2,
        login: 'barminnp@hse.ru',
        password: 'qwerty',
        role: 'creator',
        registeredEvents: [102],
        createdEvents: [103],
        createdDate: '2024-12-01T12:00:00Z',
        fullName: 'Бармин Никита Павлович',
        educationalProgram: 'Программная инженерия',
        group: '21ПМИ',
        course: 4,
    },
    {
        id: 3,
        login: 'koposovaa@edu.hse.ru',
        password: 'secret123',
        role: 'user',
        registeredEvents: [],
        createdEvents: [],
        createdDate: '2025-02-01T10:00:00Z',
        fullName: 'Копосов Андрей Алексеевич',
        educationalProgram: 'Цифровая экономика',
        group: '23ЦЭ',
        course: 2,
    },
    {
        id: 4,
        login: 'morozovaap@hse.ru',
        password: 'pass123',
        role: 'creator',
        registeredEvents: [101, 102],
        createdEvents: [101],
        createdDate: '2024-11-15T14:30:00Z',
        fullName: 'Морозова Алёна Петровна',
        educationalProgram: 'Цифровая экономика',
        group: '23ЦЭ',
        course: 2,
    },
    {
        id: 5,
        login: 'ivanovii@edu.hse.ru',
        password: 'password',
        role: 'user',
        registeredEvents: [],
        createdEvents: [],
        createdDate: '2025-01-20T08:15:00Z',
        fullName: 'Иванов Илья Иванович',
        educationalProgram: 'Системный анализ и управление данными',
        group: '22СА',
        course: 3,
    },
    {
        id: 6,
        login: 'petrovav@hse.ru',
        password: '123456',
        role: 'user',
        registeredEvents: [103],
        createdEvents: [],
        createdDate: '2025-02-10T12:00:00Z',
        fullName: 'Петрова Валерия Дмитриевна',
        educationalProgram: 'Прикладная математика и информатика',
        group: '21ПМИ',
        course: 4,
    },
    {
        id: 7,
        login: 'sidorovds@edu.hse.ru',
        password: 'test123',
        role: 'user',
        registeredEvents: [],
        createdEvents: [],
        createdDate: '2025-03-01T09:00:00Z',
        fullName: 'Сидоров Даниил Сергеевич',
        educationalProgram: 'Программная инженерия',
        group: '23ПИ',
        course: 2,
    },
    {
        id: 8,
        login: 'alekseevai@edu.hse.ru',
        password: 'securePass',
        role: 'user',
        registeredEvents: [101],
        createdEvents: [],
        createdDate: '2024-10-01T10:30:00Z',
        fullName: 'Алексеева Инна Александровна',
        educationalProgram: 'Финансы и кредит',
        group: '21ФК',
        course: 3,
    },
    {
        id: 9,
        login: 'kuznetsovs@edu.hse.ru',
        password: 'studentPass',
        role: 'user',
        registeredEvents: [],
        createdEvents: [],
        createdDate: '2025-01-10T11:00:00Z',
        fullName: 'Кузнецов Семён Владимирович',
        educationalProgram: 'Бизнес-информатика',
        group: '22БИ',
        course: 3,
    },
    {
        id: 10,
        login: 'sokolovaa@edu.hse.ru',
        password: 'student123',
        role: 'user',
        registeredEvents: [],
        createdEvents: [],
        createdDate: '2025-02-20T14:45:00Z',
        fullName: 'Соколова Алиса Артёмовна',
        educationalProgram: 'Прикладная политология',
        group: '23ПО',
        course: 2,
    },
];
